kotlin.code.style=official

# The IntelliJ Platform Gradle Plugin warns that the Kotlin stdlib is added automatically and may
# conflict with the stdlib bundled in the IntelliJ Platform (see https://jb.gg/intellij-platform-kotlin-stdlib).
kotlin.stdlib.default.dependency=false

# Modify this or delete
localIdePath=$1

org.gradle.java.installations.paths=$2

org.gradle.java.home=$3
